version: '3'
services:

  web:
    image: nginx
    volumes:
     - ./nginx/nginx-custom.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "443:80"
    environment:
     - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  service:
    build:
      context: ./seed
      dockerfile: Dockerfile
    command: /bin/sh ./run.sh
    ports:
      - "5000:5000"